pipeline{
	agent any
	
	stages{
	
		stage('Compile Stage'){
			steps{
				
					sh '''
          cd StudentTest
          mvn compile 
    '''
		    }
	    }
	    
	    stage('Test Stage'){
			steps{
			
				 junit 'StudentTest/target/surefire-reports/*.xml'
		    }
	    }
	    
	    
		stage('QA test Stage'){
			steps{
				
					sh '''
          cd StudentTest
          mvn clean test package sonar:sonar
    '''
		    }
	    }
	    
	    
		stage('Deploy Stage'){
			steps{
				
				echo "Deploy stage"
		    }
	    }
	    
	    
	 }
	 
}