pipeline{
	agent any
	
	stages{
	
		stage('Compile Stage'){
			steps{
				
					sh '''
          cd StudentTest
          mvn compile test package sonar:sonar
    '''
		    }
	    }
	    stage('deploy Stage'){
			steps{
				
					sh '''
          cd StudentTest
          mvn deploy
    '''
		    }
	    }		
	}
	 post {
      always {
        junit 'StudentTest/target/surefire-reports/*.xml'
      }
   } 
}